image: node:8.12

cache:
  paths:
  - node_modules/

stages:
  - lint
  - build

test_build:
  stage: build
  script:
   - npm install
   - npm run build 

lint:
    stage: lint
    script:
     - npm install
     - npm run lint
